"""Canonical dataset schema used across dataprep pipelines."""

RECORD_NUMBER_COLUMN = "record_number"
ADDRESS_COLUMN = "address"
LATITUDE_COLUMN = "latitude"
LONGITUDE_COLUMN = "longitude"
GEOCODED_ADDRESS_COLUMN = "geocoded_address"
PAID_COLUMN = "paid"
OUTSTANDING_COLUMN = "outstanding"
SCRAPE_STATUS_COLUMN = "scrape_status"
TREE_TYPES_COLUMN = "tree_types"
DATE_COLUMN = "date"
DATE_ISO_COLUMN = "date_iso"

SCRAPED_RECORDS_TABLE = "scraped_records"
GEOCODED_RECORDS_TABLE = "geocoded_records"
SCRAPED_FEES_TABLE = "scraped_fees"
PARSED_TREES_TABLE = "parsed_trees"
OUTPUT_TABLE = "output"

GEOCODE_OUTPUT_COLUMNS = [
    RECORD_NUMBER_COLUMN,
    ADDRESS_COLUMN,
    LATITUDE_COLUMN,
    LONGITUDE_COLUMN,
    GEOCODED_ADDRESS_COLUMN,
]

FEE_OUTPUT_COLUMNS = [
    RECORD_NUMBER_COLUMN,
    PAID_COLUMN,
    OUTSTANDING_COLUMN,
    SCRAPE_STATUS_COLUMN,
]

PARSE_TREES_OUTPUT_COLUMNS = [
    RECORD_NUMBER_COLUMN,
    TREE_TYPES_COLUMN,
]
